# Rozne nastavenia aplikacie, 
# nacitavajuce sa do premennej -> APP_CONFIG['nazov_nastavenia']

processors:

  # Trieda spracuvajuca stahovanie mailov a ukladanie do db
  download: ImapDownloadProcessor

  # Nazov triedy spracuvajucej prilohy emailu, rozkodovanie
  decode: ZipDecodeProcessor

  # Nazov triedy spracovavajucej transakcie
  extract: SlspHbExtractProcessor'